---
#
# Ansible managed
#
repository:
  description: Role for installing VictoriaMetrics Cluster
  homepage: https://buluma.github.io/
  topics: victoriametrics, prometheus, ansible, molecule, tox, playbook, hacktoberfest
